/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package My_Forms;

import My_Classes.Member;
import java.awt.Color;
import java.awt.HeadlessException;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.Icon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @member tamda
 */


public class ReturnBookForm extends javax.swing.JFrame {

    /**
     * Creates new form MembersListForm
     */
    
    My_Classes.Member member = new My_Classes.Member();
    My_Classes.Func_Class func = new My_Classes.Func_Class();
    My_Classes.Book book = new My_Classes.Book();
    My_Classes.IssueBook issueBook = new My_Classes.IssueBook();
    
    // các biến này giúp check nếu sách và tv tồn tại
    boolean bookExist = false;
    boolean memberExist = false;
    
    String imagePath = "";
    
    public ReturnBookForm() {
        initComponents();
        //Căn giữa form
        this.setLocationRelativeTo(null);
        
        // thêm border vào panel
        Border panelHeaderBorder = BorderFactory.createMatteBorder(3, 3, 3, 3, new Color(108,122,137));
        jPanel1.setBorder(panelHeaderBorder);
        
        // Hiển thị ảnh ở trên đầu
        func.displayImage(90, 60,null
                , "/My_Images/organizer.png", jLabel_FormTitle);
        
        // Thêm border trắng vào dưới tên sách và tv jlabel
        setBorderToJlable(jLabel_BookName_, Color.white); 
        setBorderToJlable(jLabel_MemberName_, Color.white);
        
        // custom jtable
        func.customeTable(jTable_IssuedBooks_);
        
        //customize jtable header row
        func.customeTableHeader(jTable_IssuedBooks_, new Color(34,167,240), 15);
        
        // 
        populateJTableWithIssuedBooks("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel_FormTitle = new javax.swing.JLabel();
        jLabel_CloseForm_ = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton_Lost_ = new javax.swing.JButton();
        jDateChooser_IssueDate = new com.toedter.calendar.JDateChooser();
        jLabel_BookName_ = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel_MemberName_ = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jDateChooser_Return_Date = new com.toedter.calendar.JDateChooser();
        jSpinner_BookID = new javax.swing.JSpinner();
        jSpinner_MemberID = new javax.swing.JSpinner();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_Note = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_IssuedBooks_ = new javax.swing.JTable();
        jButton_Return_ = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jComboBox_Status_ = new javax.swing.JComboBox<>();
        jButton_Delete_ = new javax.swing.JButton();

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Họ và Tên:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel_FormTitle.setBackground(new java.awt.Color(108, 122, 137));
        jLabel_FormTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel_FormTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_FormTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_FormTitle.setText("Trả Sách ");
        jLabel_FormTitle.setOpaque(true);

        jLabel_CloseForm_.setBackground(new java.awt.Color(108, 122, 137));
        jLabel_CloseForm_.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel_CloseForm_.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_CloseForm_.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_CloseForm_.setText("X");
        jLabel_CloseForm_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_CloseForm_.setOpaque(true);
        jLabel_CloseForm_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_CloseForm_MouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setText("Ngày mượn:");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setText("Chọn Trạng Thái Sách:");

        jButton_Lost_.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton_Lost_.setText("Mất");
        jButton_Lost_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Lost_ActionPerformed(evt);
            }
        });

        jDateChooser_IssueDate.setEnabled(false);

        jLabel_BookName_.setForeground(new java.awt.Color(51, 51, 255));
        jLabel_BookName_.setText("Tên Sách");
        jLabel_BookName_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_BookName_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_BookName_MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_BookName_MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_BookName_MouseExited(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setText("ID Thành Viên:");

        jLabel_MemberName_.setForeground(new java.awt.Color(51, 51, 255));
        jLabel_MemberName_.setText("Tên Thành Viên");
        jLabel_MemberName_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_MemberName_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_MemberName_MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_MemberName_MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_MemberName_MouseExited(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setText("Ngày trả:");

        jSpinner_BookID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jSpinner_BookID.setEnabled(false);

        jSpinner_MemberID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jSpinner_MemberID.setEnabled(false);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setText("Ghi chú:");

        jTextArea_Note.setColumns(20);
        jTextArea_Note.setRows(5);
        jScrollPane1.setViewportView(jTextArea_Note);

        jTable_IssuedBooks_.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable_IssuedBooks_.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable_IssuedBooks_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_IssuedBooks_MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable_IssuedBooks_);

        jButton_Return_.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton_Return_.setText("Trả");
        jButton_Return_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Return_ActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel16.setText("ID Sách:");

        jComboBox_Status_.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBox_Status_.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Issued", "Returned", "Lost" }));
        jComboBox_Status_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_Status_ActionPerformed(evt);
            }
        });

        jButton_Delete_.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton_Delete_.setText("Xóa");
        jButton_Delete_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Delete_ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel_FormTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_CloseForm_, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel16))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_BookName_)
                                    .addComponent(jLabel_MemberName_)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jSpinner_BookID, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                                        .addComponent(jSpinner_MemberID))))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton_Return_, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                        .addComponent(jDateChooser_IssueDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jDateChooser_Return_Date, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(77, 77, 77))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton_Delete_, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_Lost_, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox_Status_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_FormTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_CloseForm_, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox_Status_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSpinner_BookID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_BookName_)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(49, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinner_MemberID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_MemberName_)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateChooser_IssueDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateChooser_Return_Date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_Return_, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_Lost_, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_Delete_, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_CloseForm_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_CloseForm_MouseClicked
        //Đóng form
        this.dispose();
    }//GEN-LAST:event_jLabel_CloseForm_MouseClicked

    private void jButton_Lost_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Lost_ActionPerformed
        // TH Sách bị mất
        // chuyển trang thái về lost
        // và cập nhật số lương
        // số  lượng - 1
        // khi sách mất thì không đc thay đổi ngày trả    
        int bookId = (int) jSpinner_BookID.getValue();
        int memberId = (int) jSpinner_MemberID.getValue();
        String note = jTextArea_Note.getText();
        
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        
        try {
            String returnDate = dateFormat.format(jDateChooser_Return_Date.getDate()); 
           
            
            String issueDate = dateFormat.format(jDateChooser_IssueDate.getDate());
            
            
                issueBook.updateIssue(bookId, memberId, "lost", issueDate, returnDate, note);       
                
                //Cập nhật số lượng -1 
                int quantity = new My_Classes.Book().getBookById(bookId).getQuantity(); // lấy số lượng sách
                book.setQuantity_Minus_One(bookId, quantity - 1); //cập nhật só lượng sách
                //Tải lại 
                jSpinner_BookID.setValue(0);
                jSpinner_MemberID.setValue(0);
                jLabel_BookName_.setText("Tên Sách");
                jLabel_MemberName_.setText("Tên Thành Viên");
                jDateChooser_IssueDate.setDate(new Date());
                jDateChooser_Return_Date.setDate(new Date());
                jTextArea_Note.setText("");
            

                 
        } catch(HeadlessException | NullPointerException ex) {
            JOptionPane.showMessageDialog(null, "Hãy chon sách từ bảng","Chọn sách" ,2);
        } catch (SQLException ex) {
            Logger.getLogger(ReturnBookForm.class.getName()).log(Level.SEVERE, null, ex);
        }

                
    }//GEN-LAST:event_jButton_Lost_ActionPerformed

    private void jLabel_BookName_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_BookName_MouseClicked
        //Hiển thị thông tin thẻ sách
        int bookId =(int) jSpinner_BookID.getValue();
        BookInfoCardForm bookInfoCardForm = new BookInfoCardForm(bookId);
        bookInfoCardForm.setVisible(true);
    }//GEN-LAST:event_jLabel_BookName_MouseClicked

    private void jLabel_MemberName_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MemberName_MouseClicked
        //Hiển thị thông tin thẻ thành viên
        int memberId =(int) jSpinner_MemberID.getValue();
        MemberInfoCardForm memberInfoCardForm = new MemberInfoCardForm(memberId);
        memberInfoCardForm.setVisible(true);
    }//GEN-LAST:event_jLabel_MemberName_MouseClicked

    private void jLabel_BookName_MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_BookName_MouseEntered
        // Thêm border  vào dưới tên sách jlabel
        setBorderToJlable(jLabel_BookName_,  new Color(51,102,255));
    }//GEN-LAST:event_jLabel_BookName_MouseEntered

    private void jLabel_MemberName_MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MemberName_MouseEntered
        // Thêm border  vào dưới tên tv jlabel
        setBorderToJlable(jLabel_MemberName_,  new Color(51,102,255));
    }//GEN-LAST:event_jLabel_MemberName_MouseEntered

    private void jLabel_BookName_MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_BookName_MouseExited
        // Thêm border trắng vào dưới tên sách jlabel
        setBorderToJlable(jLabel_BookName_, Color.white);
    }//GEN-LAST:event_jLabel_BookName_MouseExited

    private void jLabel_MemberName_MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_MemberName_MouseExited
        // Thêm border trắng vào dưới tên tv jlabel
        setBorderToJlable(jLabel_MemberName_, Color.white);
    }//GEN-LAST:event_jLabel_MemberName_MouseExited

    private void jTable_IssuedBooks_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_IssuedBooks_MouseClicked
        // Hiển thị Hàng đã chọn

        //Get the selected row index
        int index = jTable_IssuedBooks_.getSelectedRow();

        //get values
        int bookId = Integer.parseInt(jTable_IssuedBooks_.getValueAt(index, 0).toString());
        
        int memberId = Integer.parseInt(jTable_IssuedBooks_.getValueAt(index, 1).toString());
        
        My_Classes.Book selectedBook;
        My_Classes.Member selectedMember ;
        try {
            selectedBook = book.getBookById(bookId);
            // Hiển thị tên sách
            jLabel_BookName_.setText(selectedBook.getName());
            jSpinner_BookID.setValue(selectedBook.getId());
            
            selectedMember =  member.getMemberById(memberId);
            // Hiển thị tên tv
            
            jLabel_MemberName_.setText(selectedMember.getName());
            jSpinner_MemberID.setValue(selectedMember.getId());
            
                String issuedDate = jTable_IssuedBooks_.getValueAt(index, 3).toString();
                String returnDate = jTable_IssuedBooks_.getValueAt(index, 4).toString();
//                String status = jTable_IssuedBooks_.get   ValueAt(index, 4).toString();
                String note = jTable_IssuedBooks_.getValueAt(index, 5).toString();
            
            // Hiển thị ngày
            Date issDate = new SimpleDateFormat("yyyy-MM-dd").parse(issuedDate);
            jDateChooser_IssueDate.setDate(issDate);
            
            Date rtnDate = new SimpleDateFormat("yyyy-MM-dd").parse(returnDate);
            jDateChooser_Return_Date.setDate(rtnDate);
            
            jTextArea_Note.setText(note);
                
        } catch (SQLException ex) {
            Logger.getLogger(ReturnBookForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(ReturnBookForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jTable_IssuedBooks_MouseClicked

    private void jButton_Return_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Return_ActionPerformed
        // trả sách
        //cập nhật ngày trả
        //ghi chú
        // và trạng thái trả    
        // NOTE: nếu thay đổi trang thái từ LOST sang RETURN bạn cần update quantity
        //hoặc ngăn chặn user thay đổi trang thái khi LOST
        int bookId = (int) jSpinner_BookID.getValue();
        int memberId = (int) jSpinner_MemberID.getValue();
        String note = jTextArea_Note.getText();
        
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        
        try {
            String returnDate = dateFormat.format(jDateChooser_Return_Date.getDate()); 
            Date rtnDate = dateFormat.parse(returnDate);
            
            String issueDate = dateFormat.format(jDateChooser_IssueDate.getDate());
            Date issDate = dateFormat.parse(issueDate);
            
            
            if(rtnDate.before(issDate)) { // nếu ngày trả trước nagyf mượn
                JOptionPane.showMessageDialog(null, "Ngày trả phải sau ngày mượn","Lỗi ngày trả" ,2);
            } else {
                issueBook.updateIssue(bookId, memberId, "returned", issueDate, returnDate, note);       
                //Tải lại 
                jSpinner_BookID.setValue(0);
                jSpinner_MemberID.setValue(0);
                jLabel_BookName_.setText("Tên Sách");
                jLabel_MemberName_.setText("Tên Thành Viên");
                jDateChooser_IssueDate.setDate(new Date());
                jDateChooser_Return_Date.setDate(new Date());
                jTextArea_Note.setText("");
            }

                 
        } catch(HeadlessException | NullPointerException | ParseException ex) {
            JOptionPane.showMessageDialog(null, "Hãy chon sách từ bảng","Chọn sách" ,2);
        }

    }//GEN-LAST:event_jButton_Return_ActionPerformed

    private void jComboBox_Status_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_Status_ActionPerformed
        //Hiển thị dữ liệu trong jtabel phụ thuộc vào giá trị trong jcombobox
        String status = jComboBox_Status_.getSelectedItem().toString();
        if(status.equals("All")) {
            status = "";
        }
        populateJTableWithIssuedBooks(status);
    }//GEN-LAST:event_jComboBox_Status_ActionPerformed

    private void jButton_Delete_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Delete_ActionPerformed
        // Xóa mượn sách từ database
        //lấy chỉ số các hàng đc chọn
        int index = jTable_IssuedBooks_.getSelectedRow();

        try {
            //lấy dữ liệu
            int bookId = Integer.parseInt(jTable_IssuedBooks_.getValueAt(index, 0).toString());
        
            int memberId = Integer.parseInt(jTable_IssuedBooks_.getValueAt(index, 1).toString());
            String issuedDate= jTable_IssuedBooks_.getValueAt(index, 3).toString();
        
            issueBook.removeFromIssuedTable(bookId, memberId, issuedDate);
            
            // dọn các ô
            jSpinner_BookID.setValue(0);
            jSpinner_MemberID.setValue(0);
            
            jLabel_BookName_.setText("Tên Sách");
            jLabel_MemberName_.setText("Tên Thành Viên");
            jDateChooser_IssueDate.setDate(new Date());
            jDateChooser_Return_Date.setDate(new Date()); 
            jTextArea_Note.setText("");
            
        } catch(Exception ex) {
            JOptionPane.showMessageDialog(null,"Chon phần muốn xóa khỏi bảng" + ex.getMessage(), "Lỗi Xóa",2);
        }
        
        
    }//GEN-LAST:event_jButton_Delete_ActionPerformed
 
    // Tạo phương thức để set border
    public void setBorderToJlable(JLabel label, Color color) {
        Border border = BorderFactory.createMatteBorder(0, 0, 1, 0, color);
        label.setBorder(border);
    }
    
    // Điền sách mượn vào bảng
    public void populateJTableWithIssuedBooks(String _status) {
        ArrayList<My_Classes.IssueBook> issueBooksList = issueBook.issuedBookList(_status);
        
        // Cột Jtable
        String[] colNames = {"Sách","T-Viên","T-Thái",  "N-Mượn", "N-Trả", "Ghi Chú"};
        
        // Hàng
        Object[][] rows = new  Object[issueBooksList.size()][colNames.length];
        
        for(int i =0 ; i<issueBooksList.size();i++) {
            rows[i][0] = issueBooksList.get(i).getIssueBookId();
            rows[i][1] = issueBooksList.get(i).getMemberId();
            rows[i][2] = issueBooksList.get(i).getStatus();
            rows[i][3] = issueBooksList.get(i).getIssueDate();
            rows[i][4] = issueBooksList.get(i).getReturnDate();
            rows[i][5] = issueBooksList.get(i).getNote();
            
           
        }
        
        DefaultTableModel model =  new DefaultTableModel(rows, colNames);
        jTable_IssuedBooks_.setModel(model);
        
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    //javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReturnBookForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReturnBookForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReturnBookForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReturnBookForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReturnBookForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Delete_;
    private javax.swing.JButton jButton_Lost_;
    private javax.swing.JButton jButton_Return_;
    private javax.swing.JComboBox<String> jComboBox_Status_;
    private com.toedter.calendar.JDateChooser jDateChooser_IssueDate;
    private com.toedter.calendar.JDateChooser jDateChooser_Return_Date;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel_BookName_;
    private javax.swing.JLabel jLabel_CloseForm_;
    private javax.swing.JLabel jLabel_FormTitle;
    private javax.swing.JLabel jLabel_MemberName_;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner_BookID;
    private javax.swing.JSpinner jSpinner_MemberID;
    private javax.swing.JTable jTable_IssuedBooks_;
    private javax.swing.JTextArea jTextArea_Note;
    // End of variables declaration//GEN-END:variables
}
